const DISABLE_DOCUMENT_PROCESSING =
  process.env.DISABLE_DOCUMENT_PROCESSING === "true";

const NEXT_PUBLIC_DISABLE_DOCUMENT_PROCESSING =
  process.env.NEXT_PUBLIC_DISABLE_DOCUMENT_PROCESSING === "true";

export const isDocumentProcessingDisabled =
  DISABLE_DOCUMENT_PROCESSING || NEXT_PUBLIC_DISABLE_DOCUMENT_PROCESSING;

export { DISABLE_DOCUMENT_PROCESSING, NEXT_PUBLIC_DISABLE_DOCUMENT_PROCESSING };
